"""V7_2_INITIAL_DATABASE

Revision ID: 15033d5d9c4f
Revises: 
Create Date: 2026-03-14 20:45:33.760340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15033d5d9c4f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chord_name', sa.String(length=28), nullable=False),
    sa.Column('chord_class', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre_name', sa.String(length=50), nullable=False),
    sa.Column('default_tempo', sa.Integer(), nullable=False),
    sa.Column('time_signature', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('genre_name')
    )
    op.create_table('motifs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('motif_name', sa.String(length=50), nullable=False),
    sa.Column('sequence_data', sa.Text(), nullable=False),
    sa.Column('motif_class', sa.Enum('OPENING', 'VERSE', 'PRE_CHORUS', 'CHORUS', 'BUILD', 'DE_ESCALATION', 'BRIDGE', 'ENTROPIC', 'REST', 'OUTRO', name='motifclass'), nullable=False),
    sa.Column('phrase_latency', sa.Float(), nullable=True),
    sa.Column('motif_pivot_offset', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scale_name', sa.String(length=50), nullable=False),
    sa.Column('default_root_note', sa.Integer(), nullable=False),
    sa.Column('intervals', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('song_blueprints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_class', sa.Enum('OPENING', 'VERSE', 'PRE_CHORUS', 'CHORUS', 'BUILD', 'DE_ESCALATION', 'BRIDGE', 'ENTROPIC', 'REST', 'OUTRO', name='blockclass'), nullable=False),
    sa.Column('block_position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_name', sa.String(length=100), nullable=False),
    sa.Column('track_class', sa.Enum('KICK', 'SNARE', 'HIHAT', 'PERCUSSION', 'BASS', 'MELODIC_LEAD', 'PAD_ATMOSPHERE', 'FX', name='trackclass'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setting_key', sa.String(length=50), nullable=False),
    sa.Column('setting_value', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artist_genre_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('affinity_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chord_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chord_id', sa.Integer(), nullable=False),
    sa.Column('pitch_value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chord_id'], ['chords.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compositions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genre_blueprint_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('blueprint_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['blueprint_id'], ['song_blueprints.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genre_track_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('selection_weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('motif_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('motif_id', sa.Integer(), nullable=False),
    sa.Column('chord_id', sa.Integer(), nullable=True),
    sa.Column('pitch_value', sa.Integer(), nullable=False),
    sa.Column('beat_position', sa.Float(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('micro_offset', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['chord_id'], ['chords.id'], ),
    sa.ForeignKeyConstraint(['motif_id'], ['motifs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('motif_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('motif_id', sa.Integer(), nullable=False),
    sa.Column('occurence_count', sa.Integer(), nullable=True),
    sa.Column('last_played', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['motif_id'], ['motifs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('track_motif_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('motif_id', sa.Integer(), nullable=False),
    sa.Column('selection_weight', sa.Float(), nullable=False),
    sa.Column('octave_shift', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['motif_id'], ['motifs.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('track_scale_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('scale_id', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['scale_id'], ['scales.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_motif_id', sa.Integer(), nullable=False),
    sa.Column('to_motif_id', sa.Integer(), nullable=False),
    sa.Column('transition_weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['from_motif_id'], ['motifs.id'], ),
    sa.ForeignKeyConstraint(['to_motif_id'], ['motifs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transitions')
    op.drop_table('track_scale_map')
    op.drop_table('track_motif_map')
    op.drop_table('motif_stats')
    op.drop_table('motif_notes')
    op.drop_table('genre_track_map')
    op.drop_table('genre_blueprint_map')
    op.drop_table('compositions')
    op.drop_table('chord_notes')
    op.drop_table('artist_genre_map')
    op.drop_table('user_preferences')
    op.drop_table('tracks')
    op.drop_table('song_blueprints')
    op.drop_table('scales')
    op.drop_table('motifs')
    op.drop_table('genres')
    op.drop_table('chords')
    op.drop_table('artists')
    # ### end Alembic commands ###
