"""Add rest_duration and rest_suffix to Motif

Revision ID: 62d39c33c749
Revises: 86aefad12eaa
Create Date: 2026-04-30 17:18:33.491995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62d39c33c749'
down_revision: Union[str, Sequence[str], None] = '86aefad12eaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('motifs', sa.Column('rest_duration', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('motifs', sa.Column('rest_suffix', sa.Float(), server_default='0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('motifs', 'rest_suffix')
    op.drop_column('motifs', 'rest_duration')
    # ### end Alembic commands ###
