"""add_motif_tag_column

Revision ID: 86aefad12eaa
Revises: 9ddad3503e11
Create Date: 2026-04-08 06:51:44.199885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86aefad12eaa'
down_revision: Union[str, Sequence[str], None] = '9ddad3503e11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('motifs', sa.Column('motif_tag', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('motifs', 'motif_tag')
    # ### end Alembic commands ###
