"""Sync Updated BlockClass and MotifClass Enums

Revision ID: 8b4c5ba04ef7
Revises: b4707512294f
Create Date: 2026-03-16 23:23:30.645206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b4c5ba04ef7'
down_revision: Union[str, Sequence[str], None] = 'b4707512294f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
