"""drop_user_preferences_table

Revision ID: 9ddad3503e11
Revises: 5c4dae6973d4
Create Date: 2026-03-29 03:50:14.385503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9ddad3503e11'
down_revision: Union[str, Sequence[str], None] = '5c4dae6973d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_artist_genre', 'artist_genre_map', ['artist_id', 'genre_id'])
    op.alter_column('compositions', 'artist_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('compositions_ibfk_1'), 'compositions', type_='foreignkey')
    op.create_foreign_key(None, 'compositions', 'artists', ['artist_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint('uix_genre_blueprint', 'genre_blueprint_map', ['genre_id', 'blueprint_id'])
    op.drop_constraint(op.f('genre_blueprint_map_ibfk_1'), 'genre_blueprint_map', type_='foreignkey')
    op.drop_constraint(op.f('genre_blueprint_map_ibfk_2'), 'genre_blueprint_map', type_='foreignkey')
    op.create_foreign_key(None, 'genre_blueprint_map', 'genres', ['genre_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'genre_blueprint_map', 'song_blueprints', ['blueprint_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('uix_genre_track', 'genre_track_map', ['genre_id', 'track_id'])
    op.drop_constraint(op.f('genre_track_map_ibfk_1'), 'genre_track_map', type_='foreignkey')
    op.drop_constraint(op.f('genre_track_map_ibfk_2'), 'genre_track_map', type_='foreignkey')
    op.create_foreign_key(None, 'genre_track_map', 'tracks', ['track_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'genre_track_map', 'genres', ['genre_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('motif_notes_ibfk_1'), 'motif_notes', type_='foreignkey')
    op.create_foreign_key(None, 'motif_notes', 'chords', ['chord_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint('uix_track_motif', 'track_motif_map', ['track_id', 'motif_id'])
    op.drop_constraint(op.f('track_motif_map_ibfk_2'), 'track_motif_map', type_='foreignkey')
    op.drop_constraint(op.f('track_motif_map_ibfk_1'), 'track_motif_map', type_='foreignkey')
    op.create_foreign_key(None, 'track_motif_map', 'motifs', ['motif_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'track_motif_map', 'tracks', ['track_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('uix_track_scale', 'track_scale_map', ['track_id', 'scale_id'])
    op.drop_constraint(op.f('track_scale_map_ibfk_2'), 'track_scale_map', type_='foreignkey')
    op.drop_constraint(op.f('track_scale_map_ibfk_1'), 'track_scale_map', type_='foreignkey')
    op.create_foreign_key(None, 'track_scale_map', 'scales', ['scale_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'track_scale_map', 'tracks', ['track_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('transitions_ibfk_2'), 'transitions', type_='foreignkey')
    op.drop_constraint(op.f('transitions_ibfk_1'), 'transitions', type_='foreignkey')
    op.create_foreign_key(None, 'transitions', 'motifs', ['to_motif_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'transitions', 'motifs', ['from_motif_id'], ['id'], ondelete='CASCADE')
    op.drop_table('user_preferences')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transitions', type_='foreignkey')
    op.drop_constraint(None, 'transitions', type_='foreignkey')
    op.create_foreign_key(op.f('transitions_ibfk_1'), 'transitions', 'motifs', ['from_motif_id'], ['id'])
    op.create_foreign_key(op.f('transitions_ibfk_2'), 'transitions', 'motifs', ['to_motif_id'], ['id'])
    op.drop_constraint(None, 'track_scale_map', type_='foreignkey')
    op.drop_constraint(None, 'track_scale_map', type_='foreignkey')
    op.create_foreign_key(op.f('track_scale_map_ibfk_1'), 'track_scale_map', 'scales', ['scale_id'], ['id'])
    op.create_foreign_key(op.f('track_scale_map_ibfk_2'), 'track_scale_map', 'tracks', ['track_id'], ['id'])
    op.drop_constraint('uix_track_scale', 'track_scale_map', type_='unique')
    op.drop_constraint(None, 'track_motif_map', type_='foreignkey')
    op.drop_constraint(None, 'track_motif_map', type_='foreignkey')
    op.create_foreign_key(op.f('track_motif_map_ibfk_1'), 'track_motif_map', 'motifs', ['motif_id'], ['id'])
    op.create_foreign_key(op.f('track_motif_map_ibfk_2'), 'track_motif_map', 'tracks', ['track_id'], ['id'])
    op.drop_constraint('uix_track_motif', 'track_motif_map', type_='unique')
    op.drop_constraint(None, 'motif_notes', type_='foreignkey')
    op.create_foreign_key(op.f('motif_notes_ibfk_1'), 'motif_notes', 'chords', ['chord_id'], ['id'])
    op.drop_constraint(None, 'genre_track_map', type_='foreignkey')
    op.drop_constraint(None, 'genre_track_map', type_='foreignkey')
    op.create_foreign_key(op.f('genre_track_map_ibfk_2'), 'genre_track_map', 'tracks', ['track_id'], ['id'])
    op.create_foreign_key(op.f('genre_track_map_ibfk_1'), 'genre_track_map', 'genres', ['genre_id'], ['id'])
    op.drop_constraint('uix_genre_track', 'genre_track_map', type_='unique')
    op.drop_constraint(None, 'genre_blueprint_map', type_='foreignkey')
    op.drop_constraint(None, 'genre_blueprint_map', type_='foreignkey')
    op.create_foreign_key(op.f('genre_blueprint_map_ibfk_2'), 'genre_blueprint_map', 'genres', ['genre_id'], ['id'])
    op.create_foreign_key(op.f('genre_blueprint_map_ibfk_1'), 'genre_blueprint_map', 'song_blueprints', ['blueprint_id'], ['id'])
    op.drop_constraint('uix_genre_blueprint', 'genre_blueprint_map', type_='unique')
    op.drop_constraint(None, 'compositions', type_='foreignkey')
    op.create_foreign_key(op.f('compositions_ibfk_1'), 'compositions', 'artists', ['artist_id'], ['id'])
    op.alter_column('compositions', 'artist_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_constraint('uix_artist_genre', 'artist_genre_map', type_='unique')
    op.create_table(
        'user_preferences',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('setting_key', sa.String(length=50), nullable=False),
        sa.Column('setting_value', sa.String(length=100), nullable=False)
    )
    # ### end Alembic commands ###
