"""add is_verified to chords

Revision ID: b4707512294f
Revises: 15033d5d9c4f
Create Date: 2026-03-15 00:05:16.655706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4707512294f'
down_revision: Union[str, Sequence[str], None] = '15033d5d9c4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chords', sa.Column('is_verified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chords', 'is_verified')
    # ### end Alembic commands ###
